# Site settings
title: Krishnaditya Kancharla
email: krishnaditya4@gmail.com
description: Applied AI Architect @ Google | Former GenAI Solutions Architect & ML Engineer @ AWS | MS in Data Science @ UIUC

baseurl: ""
url: "https://krishnakancharla.github.io"
github_username: krishnakancharla
linkedin_username: krishna-kancharla

# Build settings
markdown: kramdown