# Site settings
title: Krishnaditya Kancharla
email: krishnaditya4@gmail.com
description: Amazonian | Machine Learning Enthusiast | DevOps Engineer | Passionate Traveller. # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://krishnakancharla.github.io" # the base hostname & protocol for your site
twitter_username: chaibapat
github_username:  krishnakancharla

# Build settings
markdown: kramdown

#advantage - globally accessible
# for e.g. site.title , site.email, site.url etc using Liquid template can be used anywhere